baseURL = 'https://drezdin.com/'
languageCode = 'en-us'
title = 'drezdin'
theme = "hugo-theme-m10c"



[[menu.main]]
  identifier = "posts"
  name       = "Posts"
  url        = "/posts/"


[[menu.main]]
  identifier = "contact"
  name       = "Contact"
  url        = "/contact/"


[params]
author      = "drezdin"
description = "h4x0r/streamer/gamer"
avatar      = "jj-geek.jpg"      # put avatar.jpg in /static
favicon     = "/favicon.ico"

[[params.social]]
  icon = "brand-x"
  name = "X"
  url  = "https://x.com/jjfish"


[[params.social]]
  icon = "brand-kick"
  name = "Kick"
  url  = "https://kick.com/drezdin"



[[params.social]]
  icon = "brand-twitch"
  name = "Twitch"
  url  = "https://twitch.com/jjfishii"


[params.style]
  darkestColor = "#d35050"
  darkColor = "#000"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#ffffff"

