baseURL = 'https://drezdin.com/'
languageCode = 'en-us'
title = 'Drezdin'
theme = "drezdin"



[[menu.main]]
  identifier = "blog"
  name       = "Posts"
  url        = "/posts/"


[[menu.main]]
  identifier = "contact"
  name       = "Contact Me"
  url        = "/contact/"


[params]
author      = "John Janes"
description = "Senior Software Engineer â€“ Many Ninja Custom Software Solutions"
avatar      = "jj-geek.jpg"      # put avatar.jpg in /static
favicon     = "/favicon.ico"

[[params.social]]
  icon = "brand-github"
  name = "GitHub"
  url  = "https://github.com/jjanes"

[[params.social]]
  icon = "brand-x"
  name = "X"
  url  = "https://x.com/jjfish"


[[params.social]]
  icon = "brand-kick"
  name = "Kick"
  url  = "https://kick.com/drezdin"



[[params.social]]
  icon = "brand-twitch"
  name = "Twitch"
  url  = "https://twitch.com/jjfishii"


[[params.social]]
  icon = "brand-linkedin"
  name = "LinkedIn"
  url  = "https://linkedin.com/in/johnrjanes"
